services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_prod_app
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      NODE_ENV: production

